#ifndef DATANUM_TITLE_H
#define DATANUM_TITLE_H

#include "datadir_enum.h"
#include "version.h"

#if VERSION_NTSC

enum {
	TITLE_NINTENDO_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 0),
	TITLE_HUDSON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 1),
	TITLE_PRESS_START_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 2),
	TITLE_PROGRESSIVE_CHOOSE_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 3),
	TITLE_PROGRESSIVE_ON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 4),
	TITLE_PROGRESSIVE_OFF_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 5),
	TITLE_PROGRESSIVE_CURSOR_ON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 6),
	TITLE_PROGRESSIVE_CURSOR_OFF_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 7),
	TITLE_BG_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 8),
	TITLE_LOGO_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 9),
	TITLE_COPYRIGHT_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 10),
	TITLE_CHAR_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 11),
	TITLE_CUBE_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 12),
	TITLE_SKY_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 13)
};

#else

enum {
	TITLE_HUDSON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 0),
	TITLE_PROGRESSIVE_CHOOSE_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 1),
	TITLE_PROGRESSIVE_ON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 2),
	TITLE_PROGRESSIVE_OFF_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 3),
	TITLE_PROGRESSIVE_CURSOR_ON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 4),
	TITLE_PROGRESSIVE_CURSOR_OFF_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 5),
	TITLE_BG_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 6),
	TITLE_LOGO_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 7),
	TITLE_COPYRIGHT_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 8),
	TITLE_CHAR_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 9),
	TITLE_CUBE_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 10),
	TITLE_SKY_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 11),
	TITLE_LANGUAGEBG_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 12),
	TITLE_FLAG_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 13),
	TITLE_FLAG_EN_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 14),
	TITLE_FLAG_GE_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 15),
	TITLE_FLAG_FR_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 16),
	TITLE_FLAG_IT_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 17),
	TITLE_FLAG_ES_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 18),
	TITLE_PRESS_START_EN_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 19),
	TITLE_PRESS_START_GE_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 20),
	TITLE_PRESS_START_FR_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 21),
	TITLE_PRESS_START_IT_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 22),
	TITLE_PRESS_START_ES_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 23),
	TITLE_LANGUAGE_EN_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 24),
	TITLE_LANGUAGE_GE_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 25),
	TITLE_LANGUAGE_FR_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 26),
	TITLE_LANGUAGE_IT_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 27),
	TITLE_LANGUAGE_ES_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 28)
};

#endif

#endif
