#ifndef DATANUM_TITLE_H
#define DATANUM_TITLE_H

#include "datadir_enum.h"

enum {
	TITLE_NINTENDO_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 0),
	TITLE_HUDSON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 1),
	TITLE_PRESS_START_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 2),
	TITLE_PROGRESSIVE_CHOOSE_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 3),
	TITLE_PROGRESSIVE_ON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 4),
	TITLE_PROGRESSIVE_OFF_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 5),
	TITLE_PROGRESSIVE_CURSOR_ON_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 6),
	TITLE_PROGRESSIVE_CURSOR_OFF_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 7),
	TITLE_BG_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 8),
	TITLE_LOGO_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 9),
	TITLE_COPYRIGHT_ANM = DATA_MAKE_NUM(DATADIR_TITLE, 10),
	TITLE_CHAR_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 11),
	TITLE_CUBE_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 12),
	TITLE_SKY_HSF = DATA_MAKE_NUM(DATADIR_TITLE, 13),
};

#endif