#ifndef DATANUM_WIN_H
#define DATANUM_WIN_H

#include "datadir_enum.h"

enum {
	WIN_FONTJ_ANM = DATA_MAKE_NUM(DATADIR_WIN, 0),
	WIN_FONTE_ANM = DATA_MAKE_NUM(DATADIR_WIN, 1),
	WIN_CURSOR_ANM = DATA_MAKE_NUM(DATADIR_WIN, 2),
	WIN_ICON_ANM = DATA_MAKE_NUM(DATADIR_WIN, 3),
	WIN_CARDA_ANM = DATA_MAKE_NUM(DATADIR_WIN, 4),
	WIN_CARDB_ANM = DATA_MAKE_NUM(DATADIR_WIN, 5),
	WIN_FRAME1_ANM = DATA_MAKE_NUM(DATADIR_WIN, 6),
	WIN_FRAME2_ANM = DATA_MAKE_NUM(DATADIR_WIN, 7),
	WIN_FRAME3_ANM = DATA_MAKE_NUM(DATADIR_WIN, 8),
	WIN_W01_HOST_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 9),
	WIN_W02_HOST_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 10),
	WIN_W03_HOST_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 11),
	WIN_W04_HOST_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 12),
	WIN_W05_HOST_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 13),
	WIN_W06_HOST_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 14),
	WIN_TOAD_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 15),
	WIN_BOBOMB_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 16),
	WIN_SHYGUY_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 17),
	WIN_BOO_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 18),
	WIN_GOOMBA_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 19),
	WIN_BOWSER_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 20),
	WIN_KKID_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 21),
	WIN_KOOPA_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 22),
	WIN_CONDOR_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 23),
	WIN_BOO_BLUE_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 24),
	WIN_DOLPHIN_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 25),
	WIN_BOO_RED_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 26),
	WIN_THWOMP_TALK_ANM = DATA_MAKE_NUM(DATADIR_WIN, 27),
	WIN_CARD_BOX1_ICON_ANM = DATA_MAKE_NUM(DATADIR_WIN, 28),
	WIN_CARD_BOX2_ICON_ANM = DATA_MAKE_NUM(DATADIR_WIN, 29),
	WIN_CARD_BOX3_ICON_ANM = DATA_MAKE_NUM(DATADIR_WIN, 30),
	WIN_CARD_BANNER_ANM = DATA_MAKE_NUM(DATADIR_WIN, 31),
	WIN_SAVE_BG_ANM = DATA_MAKE_NUM(DATADIR_WIN, 32),
};

#endif