#ifndef _VERSION_H
#define _VERSION_H

#define VERSION_NO_ENG0 0
#define VERSION_NO_ENG1 1
#define VERSION_NO_PAL0 2
#define VERSION_NO_PAL2 3
#define VERSION_NO_JAP 4

#define VERSION_ENG (VERSION == VERSION_NO_ENG0 || VERSION == VERSION_NO_ENG1)
#define VERSION_PAL (VERSION == VERSION_NO_PAL0 || VERSION == VERSION_NO_PAL2)
#define VERSION_JAP (VERSION == VERSION_NO_JAP)
#define VERSION_NTSC (!VERSION_PAL)

#define VERSION_REV0 (VERSION == VERSION_NO_ENG0 || VERSION == VERSION_NO_PAL0 || VERSION == VERSION_NO_JAP)
#define VERSION_REV1 (!VERSION_REV0)

#endif
